name: SkyPrisonChat
author: DrakePork
description: Anything regarding private chats
version: ${project.version}
main: net.skyprison.skyprisonchat.SkyPrisonChat
api-version: 1.16
depend: [DiscordSRV]
commands:
  g:
    description: Guard Chat
    usage: /<command>
    permission: skyprisoncore.command.guard
    permission-message: §4Error:§c You do not have permission to execute this command...
  b:
    description: Builder Chat
    usage: /<command>
    permission: skyprisoncore.command.build
    permission-message: §4Error:§c You do not have permission to execute this command...
  a:
    description: Admin Chat
    usage: /<command>
    permission: skyprisoncore.command.admin
    permission-message: §4Error:§c You do not have permission to execute this command...
  s:
    description: Staff Chat
    usage: /<command>
    permission: skyprisoncore.command.staff
    permission-message: §4Error:§c You do not have permission to execute this command...
  d:
    description: Discord Chat
    usage: /<command>
    permission: skyprisoncore.command.discord
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:

